version: "3.3"
services:
  db:
    image: "postgres:12.1-alpine"
    container_name: dungeondbdev
    restart: "always"
    ports: 
      - "5432:5432"
    volumes: 
      - dungeondbdev:/var/lib/postgres/data

volumes:
  dungeondbdev: